# Generated by Django 4.0.4 on 2022-05-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_scopes_alter_scopeship_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='scopes', through='articles.Scopeship', to='articles.scope'),
        ),
    ]
