# Generated by Django 4.0.4 on 2022-05-22 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeship',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.scope'),
        ),
    ]
