# Generated by Django 4.0.4 on 2022-05-22 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_scopeship_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='articles.article'),
        ),
    ]
