# Generated by Django 4.0.4 on 2022-05-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_scopeship_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='scopeship',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='articles.scope'),
        ),
    ]
