# Generated by Django 4.0.4 on 2022-05-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_alter_scopeship_article_alter_scopeship_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(through='articles.Scopeship', to='articles.scope'),
        ),
    ]
