# Generated by Django 4.0.4 on 2022-05-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_rename_scopes_article_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
        ),
    ]
